.\"  -*- nroff -*-
.\"
.\" gnugk.1
.\"
.\" Author: 
.\"	Jan Willamowius <jan@willamowius.de> 
.\"
.Dd August 7, 2011
.Dt ADDPASSWD 1 
.Os
.Sh NAME
.Nm addpasswd
.Nd Password utility for the GNU Gatekeeper
.Sh SYNOPSIS
.Nm addpasswd
.Ar config-file
.Ar section
.Ar user
.Ar password
.Sh DESCRIPTION
Addpasswd is a tool to encrypt passwords for use in the GNU Gatekeeper config file.
Please note that this is a rather weak encryption that is easy to break for a determined attacker.
.Sh OPTIONS
.Bl -tag -width Ds
.It Ar config-file
Specify the configuration file to use. 
.It Ar section
Specify which section to write the password to. 
.It Ar user
The user name.
.It Ar password
The password to encode for this user.
.El
.Sh FILES
.Pa /etc/gatekeeper.ini
.Sh AUTHORS
The project coordinator is 
.An Jan Willamowius Aq Mt jan@willamowius.de .
.Sh SEE ALSO
.Xr gnugk 1 (and HTML manual)
.Pp
.Lk http://www.gnugk.org/ "Project homepage"
.Pp
.Lk http://www.gnugk.org/gnugk-manual.html "Manual for latest release"
.Pp
.Lk http://www.willamowius.com/gnugk-support.html "Commercial support"
