.\"  -*- nroff -*-
.\"
.\" gnugk.1
.\"
.\" Author:
.\"	Jan Willamowius <jan@willamowius.de>
.\" Man page Composer:
.\"     Ivan Lopez <ivan.n.lopez@gmail.com>
.\"
.\" Created: Tue May  15 2005
.\"
.\"
.Dd December 6, 2022
.Dt GNUGK 1
.Os
.Sh NAME
.Nm gnugk
.Nd The GNU Gatekeeper
.Sh SYNOPSIS
.Nm gnugk
.Op Fl hdrt
.Op Fl c Ar filename
.Op Fl s Ar section
.Op Fl l Ar n
.Op Fl b Ar n
.Op Fl e Ar x.x.x.x
.Op Fl u Ar name
.Op Fl d Ar name
.Op Fl rr
.Op Fl o Ar filename
.Op Fl -pid Ar filename
.Op Fl -core Ar n
.Op Fl -mlock
.Op Fl S
.Sh DESCRIPTION
The GNU Gatekeeper is an open-source project that implements a H.323 gatekeeper.
A H.323 gatekeeper controls all H.323 clients in its zone.
It allows you, among other things, to register devices, make calls, perform AAA (Authentication, Authorization and Auditing), manage configurations at runtime and traverse NAT.
.Sh OPTIONS
The behavior of the gatekeeper is determined through command line options and the configuration file.
Some command line options may override settings found in the configuration file.
For example, the option
.Fl l
overrides the setting
.Dq TimeToLive
in the configuration file.
Almost every option has a short and a long format, e.g.,
.Fl c
is the same as
.Fl -config .
.Bl -tag -width Ds
.It Fl h -help
Show all available options and quit the program.
.It Fl c -config Ar filename
Specify the configuration file to use.
.It Fl S -strict
Strict configuration check (don't start with config errors)
.It Fl s -section Ar section
Specify which main section to use in the configuration file.
The default is
.Em [Gatekeeper::Main] .
.It Fl l -timetolive Ar n
Specify the time-to-live timer (in seconds) for endpoint registration.
This overrides the setting
.Dq TimeToLive
in the configuration file.
A detailed explanation can be found in the manual.
.It Fl b -bandwidth Ar n
Specify the total bandwidth available for the gatekeeper.
Without specifying this option, bandwidth management is disabled by default.
.It Fl -pid Ar filename
Specify the pid file.
Only valid for Unix version.
.It Fl u -user Ar name
Run the gatekeeper process as this user.
Only valid for Unix versions.
.It Fl -core Ar n
(Linux only) Enable writing core dump files when the application crashes.
A core dump file will not exceed n bytes in size.
A special constant
.Dq unlimited
may also be specified.
.It Fl -mlock
(Linux only) Lock GnuGk into memory to prevent it being swaped out.
.El
.Ss Gatekeeper Mode
The options in this subsection override the settings in the [RoutedMode] section of the configuration file.
.Bl -tag -width Ds
.It Fl d -direct
Use direct endpoint call signaling.
.It Fl r -routed
Use gatekeeper routed call signaling.
.It Fl rr -h245routed
Use gatekeeper routed call signaling and H.245 control channel.
.El
.Ss Debug Information
.Bl -tag -width Ds
.It Fl o -output Ar filename
Write trace log to the specified file.
.It Fl t -trace
Set trace verbosity.
The more
.Fl t
you add, the more verbose to output.
For example, use
.Fl ttttt
to set the trace level to 5.
.El
.Sh FILES
.Pa /etc/gatekeeper.ini
.Sh AUTHORS
The project coordinator is
.An Jan Willamowius Aq Mt jan@willamowius.de .
.Sh SEE ALSO
.Xr gatekeeper.ini 5 (and HTML manual)
.Pp
.Lk https://www.gnugk.org/ "Project homepage"
.Pp
.Lk https://www.gnugk.org/gnugk-manual.html "Manual for latest release"
.Pp
.Lk https://www.willamowius.com/gnugk-support.html "Commercial support"
