string(TOLOWER "${CMAKE_SYSTEM_NAME}_${CMAKE_SYSTEM_PROCESSOR}" PLATFORM)

find_path(PTLIB_INCLUDE ptlib.h PATHS $ENV{PTLIBDIR}/include)
find_library(PTLIB_LIBRARY NAME pt_s PATHS $ENV{PTLIBDIR}/lib_${PLATFORM})

if (PTLIB_INCLUDE AND PTLIB_LIBRARY)
	MESSAGE(STATUS "PTLib found: ${PTLIB_INCLUDE}, ${PTLIB_LIBRARY}")
else ()
	MESSAGE(FATAL_ERROR "PTLib not found")
endif ()

#mark_as_advanced(PTLIB_LIBRARY PTLIB_INCLUDE)

